OPENAI_API_KEY = "ysk-proj-JrxvFIX14nNDVpxAyyU-LzhEOQRc6jDIUOBH3QQg728mbkasdFdgRC802JNRYXHnYVgz0pd2B3T3BlbkFJHJOpy9eZgQAoes-kKrvrVN-muDoVHNIQgJTNUNY37kkKyrOflHzCJO4hQtOhYQTzU6oQ5d8yoA"
PINECONE_API_KEY = "pcsk_4TZt97_QJMNwua9ox2vgP31hfuJesKmHezL1dcP6Ngcq84wQ4dEtSn81ChESeFd5VL8vXP"
PINECONE_ENV = "us-east1-gcp" 
